### ISSUE TITLE
sumneko_lua reports usage of global function as undefined.

### ISSUE THREAD

**Issue by dstanberry** [folke/lua-dev.nvim#19]
I've been using this for about a week now and it's been a great experience.

However, global lua functions defined in nvim/lua/... are no longer 'visible' to lsp if they are referenced in another file. 

The diagnostics reports "undefined global `<func>`" and I've confirmed this only happens when lua-dev is loaded.

I took a look at your dotfiles to see if I had setup my environment incorrectly, and found that you have two globals defined in util.lua (dump() and profile()) but they aren't used in any other file. 
AFAICT it should be reproducable for you if you did `dump("hello world")` in another .lua file.

Totally fine if you consider something like this a non-issue, btw.

**Comment by folke** [comment]
I actually noticed that too, but in the case of my `dump` function, I kinda like it since I use that for debugging sometimes in my plugins. That way I can see it's not defined.

Does this happen inside your nvim config too? Or just in files outside your config? Like in a plugin you're writing?

I can take a look at this once I'm back home. I'm currently traveling, but I'm back the first week of August

**Comment by dstanberry** [comment]
> 
> Does this happen inside your nvim config too? Or just in files outside your config? Like in a plugin you're writing?
> 
It happens in both cases. Like you said, I actually like when it complains for files outside my nvim config, that way I don't leave 'bad' code lying around.

**Comment by folke** [comment]
I further looked into this and this is actually on purpos.

Within your neovim config, the globals should be detected and not reported as undefined. In other project roots, we never add the neovim config as a library, since that's unwanted.

Are you using selene by any chance for linting? If so, you need to add your global functions there too to make them them recognized.

**Comment by dstanberry** [comment]
Thanks for the explanation. 👍🏾
